{
 "title": "Triton Inference Server",
 "description": "Nvidia Triton inference server metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "GPU RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes/nv_gpu_memory_total_bytes*100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_cpu_memory_used_bytes/nv_cpu_memory_total_bytes*100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of input tokens processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "business_metrics{name=\"Number of input tokens\"}"
    }
   ]
  },
  {
   "title": "Number of tokens generated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "business_metrics{name=\"Number of tokens generated\"}"
    }
   ]
  },
  {
   "title": "Flesch Readability Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "business_metrics{name=\"Flesch Readability Score\"}"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_gpu_utilization*100", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_cpu_utilization*100", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Average 30s Rate of Queue Time change (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Queue Time (ms)" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(nv_gpu_power_usage)", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Compute Time (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Compute Time (ms)" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative Inference Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "Success {{instance}}" },
    { "expr": "nv_inference_request_failure", "legendFormat": "Failure {{instance}}" }
   ]
  }
 ]
}